// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Counter, CounterTableId } from "./tables/Counter.sol";
import { LastVisit, LastVisitTableId } from "./tables/LastVisit.sol";
import { LastAffinity, LastAffinityTableId } from "./tables/LastAffinity.sol";
import { AffinityMax, AffinityMaxTableId } from "./tables/AffinityMax.sol";
import { AffinityMin, AffinityMinTableId } from "./tables/AffinityMin.sol";
import { Cat, CatTableId } from "./tables/Cat.sol";
import { Shelter, ShelterData, ShelterTableId } from "./tables/Shelter.sol";
import { OwnedBy, OwnedByTableId } from "./tables/OwnedBy.sol";
import { Location, LocationTableId } from "./tables/Location.sol";
import { Position, PositionData, PositionTableId } from "./tables/Position.sol";
import { ItemType, ItemTypeData, ItemTypeTableId } from "./tables/ItemType.sol";
import { Item, ItemTableId } from "./tables/Item.sol";
import { Balance, BalanceTableId } from "./tables/Balance.sol";
import { Affinity, AffinityTableId } from "./tables/Affinity.sol";
import { ToDo, ToDoData, ToDoTableId } from "./tables/ToDo.sol";
