// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */
enum DecoType {
  None,
  Tree,
  Food,
  Catnip
}

enum GiftType {
  None,
  Fish
}

enum StuffType {
  None,
  Poop,
  Puke,
  Fur
}

enum LocationType {
  None,
  Inventory,
  Room,
  Marketplace
}
