// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ICatSystem {
  function vistRoom(bytes32 cat, bytes32 room, uint32 x, uint32 y) external;

  function giveItem(bytes32 cat, bytes32 room, uint32 itemType, uint32 x, uint32 y) external;

  function updateCats(string calldata uri, uint32 total) external;
}
