// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IItemSystem {
  function addItemToRoom(bytes32 item, uint32 x, uint32 y) external;

  function acquireItem(uint32 itemType) external;

  function moveItem(bytes32 item, uint32 x, uint32 y) external;

  function collectItemToInventory(bytes32 item) external;
}
